# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb7fc1cac5ccdb8e3292294cf91c7e12b5e9d5bcca4b8e6660ddd4c05057a4c8d3d5026904fa0f2ac0067c527462ae5556bf28c718b4297948c140bd4a23ffc

test:
  secret_key_base: 080578c4217920e1b131754ba643781d1743a31b73833d68e49bb23a8db78eee91f1965c153509ac9cfc741ed6724615f5506771f67d71993f0379a2ae4212d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  ninefold_db: test_ninefold_app
  ninefold_user: app
  ninefold_pass: lQN_BsUDMYY0QsiJHq9p
  google_analytics_code: 'YOUR CODE HERE'
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>